### DISCUSSION TITLE
MISP Docker incredibly slow

### DISCUSSION THREAD

**Discussion by aminsenv** [MISP/MISP#9856] [Q&A]
Hello everyone

I have set up TheHive, Cortex and MISP as Docker containers. TheHive and Cortex work, even though I had to make some corrections there. MISP, however, does not work. The website can not be loaded properly and has such a long loading time (I'm talking about 60-120 seconds) and the login page looks accordingly. Can't even access the diagnostic page. Down below my docker-compose configuration

```
thehive:
    image: strangebee/thehive:5.2.2
    restart: unless-stopped
    depends_on:
      - cassandra
      - elasticsearch
      - minio
      - cortex.local
    mem_limit: 1500m
    ports:
      - "xxxx:9000:9000"
    environment:
      - CORTEX_URL=http://xxxx:9001
      - CORTEX_KEY=xxxx
      - JVM_OPTS="-Xms1024M -Xmx1024M"
    command:
      - --secret
      - "xxx"
      - "--cql-hostnames"
      - "cassandra"
      - "--index-backend"
      - "elasticsearch"
      - "--es-hostnames"
      - "elasticsearch"
      - "--s3-endpoint"
      - "http://minio:9002"
      - "--s3-access-key"
      - "minioadmin"
      - "--s3-secret-key"
      - "minioadmin"
      - "--s3-use-path-access-style"
    volumes:
      - thehivedata:/etc/thehive/application.conf
    networks:
      - SOC_NET

  cassandra:
    image: 'cassandra:4.1'
    restart: unless-stopped
    ports:
      - "xxxx:9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=TheHive
    volumes:
      - cassandradata:/var/lib/cassandra
    networks:
      - SOC_NET

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    restart: unless-stopped
    mem_limit: 512m
    ports:
      - "xxx:9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - cluster.name=hive
      - http.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - elasticsearchdata:/usr/share/elasticsearch/data
    networks:
      - SOC_NET

  minio:
    image: quay.io/minio/minio:latest
    restart: unless-stopped
    command: ["server", "/data", "--console-address", ":9002"]
    environment:
      - MINIO_ROOT_USER=xxx
      - MINIO_ROOT_PASSWORD=xxx
    ports:
      - "xxx:9002:9002"
    volumes:
      - "miniodata:/data"
    networks:
      - SOC_NET

  cortex.local:
    image: thehiveproject/cortex:3.1.7
    restart: unless-stopped
    environment:
      - job_directory=/tmp/cortex-jobs
      - docker_job_directory=/tmp/cortex-jobs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/cortex-jobs:/tmp/cortex-jobs
      - ./cortex/logs:/var/log/cortex
      - ./cortex/application.conf:/cortex/application.conf
    depends_on:
      - elasticsearch
    ports:
      - "xxx:9001:9001"
    networks:
      - SOC_NET

  misp.local:
    image: coolacid/misp-docker:core-latest
    restart: unless-stopped
    depends_on:
      - misp_mysql
    ports:
      - "xxx:7280:80"
      - "xxx:7443:443"
    volumes:
      - "./server-configs/:/var/www/MISP/app/Config/"
      - "./logs/:/var/www/MISP/app/tmp/logs/"
      - "./files/:/var/www/MISP/app/files"
      - "./ssl/:/etc/nginx/certs"
    environment:
      - MYSQL_HOST=xxx
      - MYSQL_DATABASE=xxx
      - MYSQL_USER=xxx
      - MYSQL_PASSWORD=xxx
      - MISP_ADMIN_EMAIL=xxx
      - MISP_ADMIN_PASSPHRASE=xxx
      - MISP_BASEURL=https://xxx
      - TIMEZONE=Europe/Zurich
      - "INIT=true"         
      - "CRON_USER_ID=1"   
      - "REDIS_FQDN=redis"
      - "HOSTNAME=https://xxx"
    networks:
      - SOC_NET

  misp_mysql:
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    volumes:
      - mispsqldata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=xxx
      - MYSQL_USER=xxx
      - MYSQL_PASSWORD=xxx
      - MYSQL_ROOT_PASSWORD=xxx
    networks:
      - SOC_NET

  redis:
    image: redis:7.2
    networks:
      - SOC_NET

  misp-modules:
    image: coolacid/misp-docker:modules-latest
    environment:
      - "REDIS_BACKEND=redis"
    depends_on:
      - redis
      - misp_mysql
    networks:
      - SOC_NET

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - SOC_NET

volumes:
  miniodata:
  cassandradata:
  elasticsearchdata:
  thehivedata:
  mispsqldata:
  data:

networks:
  SOC_NET:
    driver: bridge
```
    
 Checked the Docker stats for MySQL and MySQL itself:
 
```
mysql> SHOW STATUS LIKE 'Queries';
+---------------+--------+
| Variable_name | Value  |
+---------------+--------+
| Queries       | 102542 |
+---------------+--------+
1 row in set (0.00 sec)

mysql> SHOW FULL PROCESSLIST;
+------+-----------------+-----------+--------+---------+-------+------------------------+-----------------------+
| Id   | User            | Host      | db     | Command | Time  | State                  | Info                  |
+------+-----------------+-----------+--------+---------+-------+------------------------+-----------------------+
|    5 | event_scheduler | localhost | NULL   | Daemon  | 86482 | Waiting on empty queue | NULL                  |
| 3053 | root            | localhost | mispdb | Query   |     0 | init                   | SHOW FULL PROCESSLIST |
+------+-----------------+-----------+--------+---------+-------+------------------------+-----------------------+
2 rows in set (0.00 sec)
```
Anyone have any ideas?

Thanks a lot!
