### ISSUE TITLE
Support: Issue with MISP Deployment on Kubernetes: SQLSTATE[HY000] Error with External Plugin

### ISSUE THREAD

**Issue by JotaPePG** [MISP/MISP#10031]
### Support Questions

I’m deploying MISP on Rancher using Kubernetes manifests, with three containers: misp-core, misp-modules, and misp-redis. MISP uses the images provided in the misp-docker package. The login page loads fine, but when I try to log in, regardless of whether the username or password is correct, I get this error:

```bash
2024-11-08 14:42:54 Error: [PDOException] SQLSTATE[HY000]: General error: 3098 The table does not comply with the requirements by an external plugin.
Request URL: /users/login?_=1731076967879
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Model/Datasource/Database/MysqlObserverExtended.php(162): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): MysqlObserverExtended->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(641): DboSource->fetchAll()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3490): DboSource->query()
#5 /var/www/MISP/app/Model/Bruteforce.php(59): Model->query()
#6 /var/www/MISP/app/Model/Bruteforce.php(65): Bruteforce->clean()
#7 /var/www/MISP/app/Controller/UsersController.php(1209): Bruteforce->isBlocklisted()
#8 [internal function]: UsersController->login()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(500): ReflectionMethod->invokeArgs()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#12 /var/www/MISP/app/webroot/index.php(107): Dispatcher->dispatch()
#13 {main}
```

The strange part is that MISP connects to the database and creates tables without any issues, so the MySQL connection seems fine initially. But during login, it fails with the above error.
I’m using a custom DNS, and the MySQL database is version 8.0.39, running in a separate cluster within our infrastructure. The Kubernetes deployment is configured with Secrets for database credentials and a ConfigMap for other settings.
To troubleshoot, I created two local containers in the same cluster, one with MariaDB 10.11 and the other with MySQL 8.0.39 (matching the production database version). When connecting to these local containers, MISP works perfectly, including table creation and login.

I’m unsure if the issue lies with the MySQL database, an MySQL plugin, or a misconfiguration. Any help with troubleshooting this would be appreciated.

### MISP version

2.5.1

### Operating System

MISP image

### Operating System version

MISP image

### PHP version

8.2

### Browser

Chrome

### Relevant log output

```shell
2024-11-08 14:42:54 Error: [PDOException] SQLSTATE[HY000]: General error: 3098 The table does not comply with the requirements by an external plugin.
Request URL: /users/login?_=1731076967879
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Model/Datasource/Database/MysqlObserverExtended.php(162): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): MysqlObserverExtended->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(641): DboSource->fetchAll()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3490): DboSource->query()
#5 /var/www/MISP/app/Model/Bruteforce.php(59): Model->query()
#6 /var/www/MISP/app/Model/Bruteforce.php(65): Bruteforce->clean()
#7 /var/www/MISP/app/Controller/UsersController.php(1209): Bruteforce->isBlocklisted()
#8 [internal function]: UsersController->login()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(500): ReflectionMethod->invokeArgs()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#12 /var/www/MISP/app/webroot/index.php(107): Dispatcher->dispatch()
#13 {main}
```

### Extra attachments

misp-core-deployment.yaml
```yaml
# Define a 'Service' To Expose the application
apiVersion: v1
kind: Service
metadata:
  name: misp-core-service
spec:
  type: ClusterIP
  selector:
    app: misp-core
  ports:
    - protocol: "TCP"
      port: 443 # Port inside the cluster
      targetPort: 443 # Port exposed to the outside
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: misp-core-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  namespace: misp
spec:
  defaultBackend:
    service:
      name: misp-core-service
      port:
        number: 443
  ingressClassName: nginx
  rules:
    - host: dev.teste.com.br
      http:
        paths:
          - backend:
              service:
                name: misp-core-service
                port:
                  number: 443
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - dev.teste.com.br
      secretName: test-domain-certificate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: misp-core-deployment
  labels:
    app: misp-core
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: misp-core
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: misp-core
    spec:
      containers:
        - name: misp-core
          image: ghcr.io/misp/misp-docker/misp-core:v2.5.1
          securityContext:
            capabilities:
              add:
                - AUDIT_WRITE
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
            - name: https
              protocol: TCP
              containerPort: 443
          # volumeMounts:
          #   # - mountPath: /data
          #   #   name: pv-misp

          #   - mountPath: /var/www/MISP/app/Config
          #     name: pv-misp

          #   - mountPath: /var/www/MISP/app/tmp/logs
          #     name: pv-misp

          #   - mountPath: /var/www/MISP/app/files
          #     name: pv-misp

          #   - mountPath: /etc/nginx/certs
          #     name: pv-misp

          #   - mountPath: /var/www/MISP/.gnupg
          #     name: pv-misp

          #   - mountPath: /var/www/MISP/.smime
          #     name: pv-misp

          envFrom:
            - configMapRef:
                name: misp-core-envs
            - secretRef:
                name: misp-core-secrets
                optional: false
      # volumes:
      #   - name: pv-misp
      #     persistentVolumeClaim:
      #       claimName: pvc-misp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: misp-core-envs
data:
  BASE_URL: "https://dev.teste.com.br"
  DISABLE_IPV6: "true"
  REDIS_HOST: "misp-redis-service"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "cmVkaXNwYXNzd29yZA=="
  MYSQL_HOST: "mysql-cluster-teste.com"
  MYSQL_PORT: "6446"
  MYSQL_DATABASE: misp
  DEBUG: "2"
---
apiVersion: v1
kind: Secret
metadata:
  name: misp-core-secrets
type: Opaque
data:
  MYSQL_USER: "****" # HIDDEN
  MYSQL_PASSWORD: "****" # HIDDEN

```

misp-modules-deployment.yaml
```yaml
# Define a 'Service' To Expose Modules to Other Services
apiVersion: v1
kind: Service
metadata:
  name: misp-modules-service
spec:
  selector:
    app: misp-modules
  ports:
    - port: 443
      targetPort: 443
  clusterIP: None # DNS is used, so clusterIP is not needed
---
# Deployment specification begins here
apiVersion: apps/v1
kind: Deployment
metadata:
  name: misp-modules-deployment
  labels:
    app: misp-modules
spec:
  selector: # modules Pod Should contain same labels
    matchLabels:
      app: misp-modules
  strategy:
    type: Recreate
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' selectors
        app: misp-modules
    spec:
      containers:
        - name: misp-modules
          image: ghcr.io/misp/misp-docker/misp-modules:v2.4.198
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 443
              name: https
          env:
            - name: REDIS_BACKEND
              value: "misp-redis-service"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PW
              value: "cmVkaXNwYXNzd29yZA=="
```

misp-redis-deployment.yaml
```yaml
# Define a 'Service' To Expose Redis to Other Services
apiVersion: v1
kind: Service
metadata:
  name: misp-redis-service
  labels:
    app: misp-redis
    tier: database
spec:
  selector:
    app: misp-redis
    tier: database
  ports:
    - port: 6379
      targetPort: 6379
  clusterIP: None # DNS is used, so clusterIP is not needed
---
# Deployment specification begins here
apiVersion: apps/v1
kind: Deployment
metadata:
  name: misp-redis-deployment
  labels:
    app: misp-redis
    tier: database
spec:
  selector: # redis Pod Should contain same labels
    matchLabels:
      app: misp-redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' selectors
        app: misp-redis
        tier: database
    spec:
      containers:
        - name: misp-redis
          #          image: registry.k8s.io/redis:e2e
          image: valkey/valkey:7.2
          env:
            - name: REDIS_HOST
              value: "misp-redis-service"
            - name: REDIS_PASSWORD
              value: "cmVkaXNwYXNzd29yZA=="
          command: ["valkey-server", "--requirepass", "$(REDIS_PASSWORD)"]
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 6379
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
