### ISSUE TITLE
MISP & Misp Filebeat Module

### ISSUE THREAD

**Issue by AntoninHL** [MISP/MISP#5947]
Hi all,

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu
| MISP version / git hash   | v2.4.126

### Support Questions
I have an issue regading usage of MISP Filebeat module.

everything is well configured on the MISP Server.

modules.d/misp.yml:

```
- module: misp
  threat:
    enabled: true
    # API key to access MISP
    var.api_key: n....u

    # Array object in MISP response
    var.json_objects_array: "response.Attribute"

    # URL of the MISP REST API
    var.url: "https://xxxx.xxxxxx.fr/attributes/restSearch"
```

Everything worked well at first, and then it gradually stopped. Holes in the Elastic-side collection... Then for the last two days, it's been impossible to restart filebeat... 
I have a systematic error:

```
May 27 14:58:28 misp2 filebeat[3423]: 2020-05-27T14:58:28.831+0200#011ERROR#011[httpjson]#011httpjson/input.go:120#011failed to execute http client.Do: Get https://xxxx.xxxxxx.fr/attributes/restSearch: net/http: request canceled (Client.Timeout exceeded while awaiting headers)#011{"url": "https://xxxx.xxxxxx.fr/attributes/restSearch"}

May 27 14:58:28 misp2 filebeat[3423]: 2020-05-27T14:58:28.831+0200#011INFO#011[httpjson]#011httpjson/input.go:121#011httpjson input worker has stopped.#011{"url": "https://xxxx.xxxxxx.fr/attributes/restSearch"}
```

I tried from the MISP interface, via "REST Client", and I have the same error.

Thanks for your help!

A.

**Comment by mokaddem** [comment]
Hello,
I'm not sure if it's MISP related or your module.
Do you see any errors in the MISP's logs that could be linked with your issue? 
The logs are under `app/tmp/logs`.

**Comment by AntoninHL** [comment]
Hi @mokaddem 

Many thanks for your reply.

Unfortunately, there is no specific error in all the *error*.log files...

The only thing I have is:
`httpjson/input.go:120#011failed to execute http client.Do: Get https://xxxx.xxxxxx.fr/attributes/restSearch: net/http: request canceled (Client.Timeout exceeded while awaiting headers)#011{"url": "https://xxxx.xxxxxx.fr/attributes/restSearch"}`

I've been trying to figure out how to fix a mistake like this, but no answer...

I then thought that maybe I should abandon the misp module included in filebeat, and go back to something else, like associating logstash+memcached, but the only site that talks about that is not clear at all...

My only need is to connect MISP to elastic...
It's desperate to see that nothing works properly.

**Comment by mokaddem** [comment]
Do you see a connection request in the apache access logs? If you don't, there is definitely something badly configured or the filebeat integration is not stable yet.

**Comment by AntoninHL** [comment]
Yes...
xxx.xxx.xxx.xxx - - [04/Jun/2020:09:23:47 +0200] "GET /attributes/restSearch/ HTTP/1.1" 200 20825 "-" "Elastic Filebeat/7.6.2 (linux; amd64; xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; 2020-03-26 05:23:38 +0000 UTC)"

Very strange...

**Comment by mokaddem** [comment]
So you are actually doing a `GET /attributes/restSearch/` without filtering parameters. That means, you are fetching the entire dataset in one shot, which could explains the timeout.
Could you try to paginate and see if it helps?
The **200** response code is weird though.

**Comment by AntoninHL** [comment]
There is a filter in the misp.yml config file:

```
- module: misp
  threat:
    enabled: true

    # API key to access MISP
    var.api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

    # Array object in MISP response
    var.json_objects_array: "response.Attribute"

    # URL of the MISP REST API
    var.url: "https://xxx.xxx.fr/attributes/restSearch/"

    var.http_method: GET
    var.http_request_body: '{"last":"1d"}'
```
