### ISSUE TITLE
Support: Failed to read session data: redis (path: tcp://redis:6379)

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#8993]
### Support Questions

Any help is greatly appreciated!! One of our MISP instances with MISP and PHP configured to talk to `tcp://redis:6379` is experiencing server `error.log` entries for some PyMISP calls, e.g. `pymisp.untag` (sample error message below). We reset this instance to use files, but prefer this setting.

This MISP server runs in a docker container with redis running in a separate container on th same bare-metal host.

Thanks!

### MISP version

2.4.169

### Operating System

RH

### Operating System version

8.7

### PHP version

7.4.30

### Relevant log output

```shell
2023-03-31 08:48:56 Warning: Warning (2): session_start() [<a href='http://php.net/function.session-start'>function.session-start</a>]: Failed to read session data: redis (path: tcp://redis:6379) in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/CakeSession.php, line 745]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by github-germ** [comment]
@iglocska Would be great if you could help shed some light on this to track down root cause. Let me know what else I can probe please. THANKS!!

We've re-enabled PHP session handler from files to redis to revisit this issue. Clearly, we need to be on redis for concurrency issues via the WebUI (#9239) and for performance.

The WebUI issue of user single-threaded is fixed with redis sessions, and performance is much better. However, we still see the issue below.

Here's one example of an app triggering this warning. HOWEVER, we see other `pymisp` calls producing the same. Maybe looking at this one will help isolate root cause

```
Warning: Warning (2): session_start() [<a href='http://php.net/function.session-start'>function.session-start</a>]: Failed to read session data: redis (path: tcp://redis:6379) in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/CakeSession.php, line 745]
```
is some of our cron apps attempting to remove many tags by calling `pymisp.untag` which fails with:
```
ERROR Something went wrong (403): {'name': 'Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header.', 'message': 'Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header.', 'url': '/tags/removeTagFromObject'}
```
However, the transaction in the db `logs` table looks to have authenticated ok. The other `pymisp` calls with the same issue also look fine in the `logs`:
```
         id: 1912011989
      title: Successful authentication using API key (XXXX********************************XXXX)
    created: 2023-08-12 10:34:45
      model: User
   model_id: 148
     action: auth
    user_id: 0
     change: HTTP method: POST
Target: /tags/removeTagFromObject
      email: xxxx@local.net
        org: XXXX
description:
         ip: 172.x.y.z
```
