### ISSUE TITLE
Bug: 2.4.170 pymisp(controller='attributes', eventid=e) does NOT include category='Internal reference', type='link' attributes

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#9032]
### Expected behavior

 With 2.4.170 `pymisp.search('controller=attributes')` does not include `category='Internal reference', type='link'` attributes. Likewise, in the WebUI `Download as...` into MISP JSON also does NOT include that attribute type.

When same tested in 2.4.167, both `pymisp.search` and `Download as...` do include that type. We no longer have 2.4.168 or 2.4.169 easily installed here to test when what appears to be an adverse change occurred.

I had opened https://github.com/MISP/PyMISP/issues/973 and @Rafiot believes this is rooted in the MISP side.

Thanks!

### Actual behavior

Attributes with category `Internal reference` and type `link` should be included in search results for PyMISP and WebUI.

### Steps to reproduce

1. Create an event with a category `Internal reference` with type `link`attribute.
2. Call `pymisp.search('controller=attributes')` -- that attribute is not in the result.
3. WebUI `Download as...` into MISP JSON -- attribute is not included in the result.

### Version

2.4.170

### Operating System

RH

### Operating System version

8.7

### PHP version

7.4.33

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ostefano** [comment]
@github-germ been testing with pymisp==2.4.165.1 and pymisp==2.4.170 and internal reference attributes are correclty returned (misp version 2.4.170). I have been using the option `pythonify=True` though.

**Comment by github-germ** [comment]
@ostefano Thanks. What MISP server version did you test with? Let me clarify... The issue seems related to the MISP server version as it worked with 2.4.167, but now with 2.4.170 it does not.

I just retested with MISP 2.4.170, PyMISP 2.4.70 and setting `pythonify` to `True` or `False` with `pymisp.search` does NOT include the `Internal reference` attribute `type` in result.

![image](https://user-images.githubusercontent.com/8812009/234016359-673c51fa-800d-42cc-9d0b-1f3d82d4bdd5.png)

```
...
>>> import pymisp
>>> pymisp.__version__
'2.4.170'
>>> from pymisp import PyMISP
>>> import urllib3
>>> urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
>>> import warning
>>> warnings.filterwarnings("ignore", category=DeprecationWarning)
>>> misp = PyMISP(url='https://localhost, key='REDACTED', ssl=False)
>>> misp.misp_instance_version
{'version': '2.4.170', 'pymisp_recommended_version': '2.4.170', 'perm_sync': True, 'perm_sighting': True, 'perm_galaxy_editor': True, 'request_encoding': ['gzip', 'br'], 'filter_sightings': True}
>>>
>>> response = misp.search(controller = 'attributes', eventid = 2020718, pythonify=True)
>>> len(response)
1
>>> print(response[0])
<MISPAttribute(type=ip-src, value=254.254.254.254)
>>>
```

**Comment by ostefano** [comment]
@github-germ I am testing 2.4.170 as well.

```
attributes = misp.search(
    controller="attributes",
    pythonify=True,
    eventid=238,
)
print(pymisp.__version__)
print(misp.misp_instance_version)
for attr in attributes:
    if attr.category == "Internal reference":
        print(attr)
```

Output

```
2.4.170
{'version': '2.4.170', 'pymisp_recommended_version': '2.4.170', 'perm_sync': True, 'perm_sighting': True, 'perm_galaxy_editor': True, 'request_encoding': ['gzip', 'br'], 'filter_sightings': True}
<MISPAttribute(type=link, value=https://otx.alienvault.com/pulse/64154c3a55623201002a8caa)
```

**Comment by github-germ** [comment]
Very strange. It's also not included in the `MISPEvent` retrieved with `search`. What do you suggest I try next?
```
>>> response = misp.search(controller = 'events', eventid = 2020718, pythonify=True)
>>> print(response[0])
<MISPEvent(info=test #9032)
>>> import json
>>> print(response[0]['Attribute'])
[<MISPAttribute(type=ip-src, value=254.254.254.254)]
>>>
```

**Comment by ostefano** [comment]
I am at loss, to be honest.

Do you have any schema issues?
What does the diagnostic say?

What happens if you add a new attribute from the UI?

**Comment by github-germ** [comment]
```
mysql> select * from attributes where event_id=2020718 \G
*************************** 1. row ***************************
                 id: 518431703
           event_id: 2020718
          object_id: 0
    object_relation: NULL
           category: Internal reference
               type: link
             value1: https://itrack.web...
             to_ids: 0
               uuid: dbc2ea4b-c8ae-443f-bb5b-126b5c93bd36
          timestamp: 1681748954
       distribution: 0
   sharing_group_id: 0
            comment:
            deleted: 0
disable_correlation: 0
         first_seen: NULL
          last_seen: NULL
*************************** 2. row ***************************
                 id: 518432041
           event_id: 2020718
          object_id: 0
    object_relation: NULL
           category: Network activity
               type: ip-src
             value1: 254.254.254.254
             value2:
             to_ids: 0
               uuid: 6a139252-4cd8-4a64-898d-e973d78954d5
          timestamp: 1681749930
       distribution: 5
   sharing_group_id: 0
            comment:
            deleted: 0
disable_correlation: 0
         first_seen: NULL
          last_seen: NULL
2 rows in set (0.00 sec)

mysql>
```
