### ISSUE TITLE
Support: What causes MISP Sync pull "Tried to save sharing group with UUID ... but the user does not belong to it"

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#9066]
### Support Questions

We have 2 MISP instances each pulling from a remote MISP via Sync. One instance is fine, i.e. it created the Sharing Groups from the remote locally and is populating attributes into events. However, the other instance cannot create the Sharing Groups.

The following error is in the log output from `cake Server pull <userid> <serverid> full`
```
error -- Tried to save a sharing group with UUID 'R-E-DACTED' but the user does not belong to it.
error -- Tried to save a sharing group with UUID 'RE-DACT-ED' but the user does not belong to it.
```
Do you have any suggestions on what may different between our two MISP instances that prevents this second MISP from creating the Sharing Groups?

Taking a quick look at the `Model/SharingGroup.php1 where that error is logged, I see lots of knobs that need alignment, but so far I've not discovered which one(s) it could be.

### MISP version

2.4.170

### Operating System

RH

### Operating System version

8.7

### PHP version

7.4.33

### Relevant log output

```shell
2023-05-09 19:01:43 Info: Fetching eligible clusters from server #2 for pull
: []
/var/www/MISP/app/tmp/logs/[197123]: error -- Tried to save a sharing group with UUID 'RE-DACTED' but the user does not belong to it.
/var/www/MISP/app/tmp/logs/[197123]: publish -- Event (663452): REDACTED -- Event (663452) added by User "SYSTEM" (0).
/var/www/MISP/app/tmp/logs/[197123]: add -- Event pulled from Server (2) - "REDACTED MISP" - Notification by mail disabled
...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by github-germ** [comment]
Not sure if this is a user role issue. Thinking not. But here's the role of the user running the `cake`:
```
mysql> select * from roles where id=5 \G
*************************** 1. row ***************************
                      id: 5
                    name: Sync user
                 created: 2018-05-15 13:35:11
                modified: 2022-11-22 21:13:00
                perm_add: 1
             perm_modify: 1
         perm_modify_org: 1
            perm_publish: 1
           perm_delegate: 1
               perm_sync: 1
              perm_admin: 0
              perm_audit: 1
               perm_full: 0
               perm_auth: 1
         perm_site_admin: 0
      perm_regexp_access: 0
             perm_tagger: 0
           perm_template: 0
      perm_sharing_group: 1
         perm_tag_editor: 0
           perm_sighting: 1
    perm_object_template: 0
            default_role: 0
            memory_limit:
      max_execution_time: 7200
restricted_to_site_admin: 0
        perm_publish_zmq: 1
      perm_publish_kafka: 0
           perm_decaying: 1
      enforce_rate_limit: 0
        rate_limit_count: 0
      perm_galaxy_editor: 0
        perm_warninglist: 0
1 row in set (0.00 sec)

mysql> 
```
