### ISSUE TITLE
Support: MISP sync debug.log errors and lots of db logs rows as SYSTEM no user

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#9447]
### Support Questions

Why do transactions from MISP sync pulls trigger
1. stack traces in `debug.log`
2. rows created in the db `logs` table with `user_id: 0` and `org: 'SYSTEM'`?

I pinpointed these to be from MISP sync pulls with this query which resulted in all orgs being remote and identifiable to an external MISP instance we pull from.
```
select distinct(name),local from organisations where id in (select orgc_id from events where id in (select distinct(model_id) from logs where created between '2023-12-14 00:00:00' and '2023-12-14 23:59:59' and org='SYSTEM' and action='edit' and model='Event'));
```

### MISP version

2.4.181

### Operating System

RH

### Operating System version

8.8

### PHP version

7.4.33

### Relevant log output

```shell
1. See lots of half-baked rows in the db `logs` table

mysql> select count(*) from logs where created between '2023-12-14 00:00:00' and '2023-12-14 23:59:59' and org='SYSTEM';
+----------+
| count(*) |
+----------+
|     9964 |
+----------+

2. That look like this:

*************************** 1. row ***************************
         id: 1633034573
      title: Successful authentication using MyLogins External authentication key
    created: 2023-12-14 18:44:40
      model: User
   model_id: 44
     action: auth
    user_id: 0
     change: {"user_agent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/120.0.0.0 Safari\/537.36","ip":"10.103.12.159","accept_lang":"en-US,en;q=0.9","geoip":"None","ua_pattern":"mozilla\/5.0 (*windows nt 10.0*)*applewebkit*(*khtml*like*gecko*)*chrome\/* safari\/*","ua_platform":"Win10","ua_browser":"Chrome","http_method":"GET","target":"\/events\/index\/searchorg:71"}
      email:
        org: SYSTEM
description:
         ip: 10.103.12.159
1 row in set (0.00 sec)

mysql> 

4. Corresponding debug.log stack traces:

2023-12-14 18:44:40 Notice: Notice (8): Undefined index: Organisation in [/var/www/MISP/app/Model/Log.php, line 253]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
Log::createLogEntry() - APP/Model/Log.php, line 253
AppController::__customAuthentication() - APP/Controller/AppController.php, line 1162
AppController::beforeFilter() - APP/Controller/AppController.php, line 206
EventsController::beforeFilter() - APP/Controller/EventsController.php, line 68
BetterCakeEventManager::dispatch() - APP/Lib/Tools/BetterCakeEventManager.php, line 23
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 682
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 189
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 101

2023-12-14 18:44:40 Notice: Notice (8): Trying to access array offset on value of type null in [/var/www/MISP/app/Model/Log.php, line 253]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
Log::createLogEntry() - APP/Model/Log.php, line 253
AppController::__customAuthentication() - APP/Controller/AppController.php, line 1162
AppController::beforeFilter() - APP/Controller/AppController.php, line 206
EventsController::beforeFilter() - APP/Controller/EventsController.php, line 68
BetterCakeEventManager::dispatch() - APP/Lib/Tools/BetterCakeEventManager.php, line 23
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 682
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 189
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 101

2023-12-14 18:44:40 Notice: Notice (8): Undefined index: email in [/var/www/MISP/app/Model/Log.php, line 254]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
Log::createLogEntry() - APP/Model/Log.php, line 254
AppController::__customAuthentication() - APP/Controller/AppController.php, line 1162
AppController::beforeFilter() - APP/Controller/AppController.php, line 206
EventsController::beforeFilter() - APP/Controller/EventsController.php, line 68
BetterCakeEventManager::dispatch() - APP/Lib/Tools/BetterCakeEventManager.php, line 23
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 682
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 189
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 101

2023-12-14 18:44:40 Notice: Notice (8): Undefined index: id in [/var/www/MISP/app/Model/Log.php, line 255]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
Log::createLogEntry() - APP/Model/Log.php, line 255
AppController::__customAuthentication() - APP/Controller/AppController.php, line 1162
AppController::beforeFilter() - APP/Controller/AppController.php, line 206
EventsController::beforeFilter() - APP/Controller/EventsController.php, line 68
BetterCakeEventManager::dispatch() - APP/Lib/Tools/BetterCakeEventManager.php, line 23
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 682
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 189
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 101
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by github-germ** [comment]
Curious if this is related to what is seen for 3 MISP sync pulls which outout the following from the `cake` launch:
```
2023-12-07 04:20:24 Error: Failed downloading the sightings from REDACtED MISP.
[HttpSocketHttpException] Remote server returns HTTP error code 405 for URL https://REDACTED/sightings/restSearch/event
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/ServerSyncTool.php(244): ServerSyncTool->post()
#1 /var/www/MISP/app/Model/Sighting.php(1385): ServerSyncTool->fetchSightingsForEvents()
#2 /var/www/MISP/app/Model/Sighting.php(1363): Sighting->pullSightingNewWay()
#3 /var/www/MISP/app/Model/Server.php(673): Sighting->pullSightings()
#4 /var/www/MISP/app/Console/Command/ServerShell.php(147): Server->pull()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->pull()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#8 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#9 {main}
```

**Comment by github-germ** [comment]
@iglocska  These db `logs` entries triggering logging into `debug.log` as above persists in 2.4.191. What Can I do or share with you to help determine root cause and whether these can be ignored ore require some action?

Here's the same with 2.4.191 running:
```
mysql> select * from logs where created = '2024-04-29 17:45:09' and org='SYSTEM' \G
*************************** 1. row ***************************
         id: 3220006804
      title: Successful authentication using MyLogins External authentication key
    created: 2024-04-29 17:45:09
      model: User
   model_id: 74
     action: auth
    user_id: 0
     change: {"user_agent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/124.0.0.0 Safari\/537.36","ip":"10.103.12.159","accept_lang":"en-US,en;q=0.9","geoip":"None","ua_pattern":"mozilla\/5.0 (*mac os x*) applewebkit* (*khtml*like*gecko*) *chrome\/* safari\/*","ua_platform":"MacOSX","ua_browser":"Chrome","http_method":"GET","target":"\/api\/getAllApis"}
      email:
        org: SYSTEM
description:
         ip: 10.103.12.159
*************************** 2. row ***************************
         id: 3220006805
      title: Successful authentication using MyLogins External authentication key
    created: 2024-04-29 17:45:09
      model: User
   model_id: 74
     action: auth
    user_id: 0
     change: {"user_agent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/124.0.0.0 Safari\/537.36","ip":"10.103.12.159","accept_lang":"en-US,en;q=0.9","geoip":"None","ua_pattern":"mozilla\/5.0 (*mac os x*) applewebkit* (*khtml*like*gecko*) *chrome\/* safari\/*","ua_platform":"MacOSX","ua_browser":"Chrome","http_method":"GET","target":"\/rest_client_history\/index\/"}
      email:
        org: SYSTEM
description:
         ip: 10.103.12.159
*************************** 3. row ***************************
         id: 3220006806
      title: Successful authentication using MyLogins External authentication key
    created: 2024-04-29 17:45:09
      model: User
   model_id: 74
     action: auth
    user_id: 0
     change: {"user_agent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/124.0.0.0 Safari\/537.36","ip":"10.103.12.159","accept_lang":"en-US,en;q=0.9","geoip":"None","ua_pattern":"mozilla\/5.0 (*mac os x*) applewebkit* (*khtml*like*gecko*) *chrome\/* safari\/*","ua_platform":"MacOSX","ua_browser":"Chrome","http_method":"GET","target":"\/rest_client_history\/index\/1"}
      email:
        org: SYSTEM
description:
         ip: 10.103.12.159
3 rows in set (0.00 sec)

mysql>  
```
```
# grep '2024-04-29 17:45:09' debug.log
2024-04-29 17:45:09 Notice: Notice (8): Undefined index: Organisation in [/var/www/MISP/app/Model/Log.php, line 264]
2024-04-29 17:45:09 Notice: Notice (8): Trying to access array offset on value of type null in [/var/www/MISP/app/Model/Log.php, line 264]
2024-04-29 17:45:09 Notice: Notice (8): Undefined index: email in [/var/www/MISP/app/Model/Log.php, line 265]
2024-04-29 17:45:09 Notice: Notice (8): Undefined index: id in [/var/www/MISP/app/Model/Log.php, line 266]
2024-04-29 17:45:09 Notice: Notice (8): Undefined index: Organisation in [/var/www/MISP/app/Model/Log.php, line 264]
2024-04-29 17:45:09 Notice: Notice (8): Undefined index: Organisation in [/var/www/MISP/app/Model/Log.php, line 264]
2024-04-29 17:45:09 Notice: Notice (8): Trying to access array offset on value of type null in [/var/www/MISP/app/Model/Log.php, line 264]
2024-04-29 17:45:09 Notice: Notice (8): Trying to access array offset on value of type null in [/var/www/MISP/app/Model/Log.php, line 264]
2024-04-29 17:45:09 Notice: Notice (8): Undefined index: email in [/var/www/MISP/app/Model/Log.php, line 265]
2024-04-29 17:45:09 Notice: Notice (8): Undefined index: email in [/var/www/MISP/app/Model/Log.php, line 265]
2024-04-29 17:45:09 Notice: Notice (8): Undefined index: id in [/var/www/MISP/app/Model/Log.php, line 266]
2024-04-29 17:45:09 Notice: Notice (8): Undefined index: id in [/var/www/MISP/app/Model/Log.php, line 266]
# 
```
